import { useEffect, useState } from "react";
import { Download } from "lucide-react";

type Report = { key: string; size: number; uploaded: string };

type LoadState =
	| { status: "loading" }
	| { status: "error"; message: string }
	| { status: "loaded"; reports: Report[] };

const formatSize = (bytes: number) => {
	if (bytes < 1024) return `${bytes} B`;
	if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
	return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
};

const formatDate = (iso: string) => new Date(iso).toLocaleString();

export default function Reports({ onBack }: { onBack: () => void }) {
	const [state, setState] = useState<LoadState>({ status: "loading" });
	const [generating, setGenerating] = useState(false);
	const [generateError, setGenerateError] = useState("");

	async function loadReports() {
		const response = await fetch("/api/reports");
		if (!response.ok) {
			throw new Error(`Failed to load reports (${response.status})`);
		}
		const data = (await response.json()) as { reports: Report[] };
		setState({ status: "loaded", reports: data.reports });
	}

	useEffect(() => {
		let active = true;
		(async () => {
			try {
				await loadReports();
			} catch (error) {
				if (active) {
					setState({
						status: "error",
						message: error instanceof Error ? error.message : "Failed to load reports",
					});
				}
			}
		})();
		return () => {
			active = false;
		};
	}, []);

	async function generateReport() {
		setGenerating(true);
		setGenerateError("");
		const controller = new AbortController();
		const timeout = setTimeout(() => controller.abort(), 90_000);
		try {
			const response = await fetch("/api/report/pdf", {
				method: "POST",
				signal: controller.signal,
			});
			if (!response.ok) {
				throw new Error(`Failed to generate report (${response.status})`);
			}
			await loadReports();
		} catch (error) {
			const aborted = error instanceof DOMException && error.name === "AbortError";
			setGenerateError(
				aborted
					? "Timed out after 90s"
					: error instanceof Error
						? error.message
						: "Failed to generate report",
			);
		} finally {
			clearTimeout(timeout);
			setGenerating(false);
		}
	}

	return (
		<main>
			<section className="hero">
				<p className="eyebrow">Hedge Fund of Agents</p>
				<h1>Reports</h1>
				<p className="intro">
					Daily desk reports generated by Browser Rendering and stored in R2.
				</p>

				<div className="actions">
					<button type="button" onClick={onBack}>
						Back to desk
					</button>
				</div>

				{state.status === "loading" && <p className="result">Loading reports...</p>}

				{state.status === "error" && (
					<p className="result">
						<span className="error">{state.message}</span>
					</p>
				)}

				{state.status === "loaded" && state.reports.length === 0 && (
					<div className="result" style={{ flexDirection: "column", alignItems: "stretch" }}>
						<div style={{ display: "flex", gap: "0.75rem", alignItems: "center" }}>
							<span style={{ flex: 1 }}>No reports generated yet.</span>
							<button type="button" onClick={generateReport} disabled={generating}>
								{generating ? "Generating..." : "Generate report"}
							</button>
						</div>
						{generateError && (
							<strong className="error" style={{ marginTop: "0.75rem" }}>
								{generateError}
							</strong>
						)}
					</div>
				)}

				{state.status === "loaded" &&
					state.reports.map((report) => (
						<div className="result" key={report.key}>
							<span className="status-dot" />
							<div style={{ flex: 1 }}>
								<strong>{report.key}</strong>
								<time>
									{formatDate(report.uploaded)} · {formatSize(report.size)}
								</time>
							</div>
							<a
								className="icon-button"
								href={`/api/reports/${encodeURIComponent(report.key)}`}
								download
								aria-label={`Download ${report.key}`}
								title="Download"
							>
								<Download size={18} aria-hidden="true" />
							</a>
						</div>
					))}
			</section>
		</main>
	);
}
