import { useEffect, useState } from "react";

type Report = { key: string; size: number; uploaded: string };

type LoadState =
	| { status: "loading" }
	| { status: "error"; message: string }
	| { status: "loaded"; reports: Report[] };

const formatSize = (bytes: number) => {
	if (bytes < 1024) return `${bytes} B`;
	if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
	return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
};

const formatDate = (iso: string) => new Date(iso).toLocaleString();

export default function Reports({ onBack }: { onBack: () => void }) {
	const [state, setState] = useState<LoadState>({ status: "loading" });

	useEffect(() => {
		let active = true;

		(async () => {
			try {
				const response = await fetch("/api/reports");
				if (!response.ok) {
					throw new Error(`Failed to load reports (${response.status})`);
				}
				const data = (await response.json()) as { reports: Report[] };
				if (active) {
					setState({ status: "loaded", reports: data.reports });
				}
			} catch (error) {
				if (active) {
					setState({
						status: "error",
						message: error instanceof Error ? error.message : "Failed to load reports",
					});
				}
			}
		})();

		return () => {
			active = false;
		};
	}, []);

	return (
		<main>
			<section className="hero">
				<p className="eyebrow">Hedge Fund of Agents</p>
				<h1>Reports</h1>
				<p className="intro">
					Daily desk reports generated by Browser Rendering and stored in R2.
				</p>

				<div className="actions">
					<button type="button" onClick={onBack}>
						Back to desk
					</button>
				</div>

				{state.status === "loading" && <p className="result">Loading reports...</p>}

				{state.status === "error" && (
					<p className="result">
						<span className="error">{state.message}</span>
					</p>
				)}

				{state.status === "loaded" && state.reports.length === 0 && (
					<p className="result">No reports generated yet.</p>
				)}

				{state.status === "loaded" &&
					state.reports.map((report) => (
						<div className="result" key={report.key}>
							<span className="status-dot" />
							<div style={{ flex: 1 }}>
								<strong>{report.key}</strong>
								<time>
									{formatDate(report.uploaded)} · {formatSize(report.size)}
								</time>
							</div>
							<a href={`/api/reports/${encodeURIComponent(report.key)}`} download>
								Download
							</a>
						</div>
					))}
			</section>
		</main>
	);
}
